# Generated by Django 2.2.19 on 2022-08-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220817_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='adress',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug'),
        ),
    ]
