# Generated by Django 2.2.19 on 2022-08-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220818_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='adress',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
