# Generated by Django 2.2.19 on 2022-08-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220818_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='adress',
            new_name='slug',
        ),
    ]
